### ISSUE TITLE
Emacs error reporting

### ISSUE THREAD

**Issue by sheyll** [RefactoringTools/HaRe#18]
When trying any refactoring from the "Refactorer" menu I get nothing but errors.

From the _Messages_ buffer:

Res=RefSet
equal: Wrong type argument: sequencep, RefSet
Running...done
Res=cabal-helper-wrapper:
equal: Wrong type argument: sequencep, cabal-helper-wrapper:

I use stack lts-4.0 with a recent ghc emacs plugin.

I installed hare and ghc-mod via stack.

**Comment by alanz** [comment]
I think you have to install cabal-helper too.
