### ISSUE TITLE
Add support for passing options to ghc (aka -g option)

### ISSUE THREAD

**Issue by alfa07** [RefactoringTools/HaRe#20]
The problem is to integrate HaRe with existing build system which relies on --package-db to provide package locations.

**Comment by alanz** [comment]
Are you talking about stack, or something else?

In either case, I will add this feature it has been planned for, just interested.

**Comment by alanz** [comment]
I am going to work in the `-g` option as used in ghc-mod. would it make sense to bring in the rest of the ghc-mod options too, such as
```
 --line-prefix OUT,ERR    Output prefixes
  --with-ghc ARG           GHC executable to use (default: "ghc")
  --with-ghc-pkg ARG       ghc-pkg executable to use (only needed when guessing
                           from GHC path fails) (default: "ghc-pkg")
  --with-cabal ARG         cabal-install executable to use (default: "cabal")
  --with-stack ARG         stack executable to use (default: "stack")
```

**Comment by alanz** [comment]
@alfa07 please try https://github.com/alanz/HaRe/tree/wip which has the options above,  passed through to ghc-mod, and let me know if I can merge it into master
