### ISSUE TITLE
The HaRe library gets compiled twice

### ISSUE THREAD

**Issue by Lysxia** [RefactoringTools/HaRe#39]
The code for both the library and the executable is in the same directory. When compiling the executable, GHC does not look in the HaRe library it just built, but instead thinks that the code in `src/` is part of the executable and compiles it again from scratch.

The compilation time of the package can be halved by moving the library or the executable in separate directories.

**Comment by alanz** [comment]
This time can also be halved by adding HaRe as a dependency to the exe.

The problem is that then HaRe cannot refactor itself, in the sense that if something is renamed in the main library code it will not be renamed in the tests at the same time.

The correct solution is to manage the calculation of the module graph to include the lib dependencies on all the assorted test and exe portions too.

**Comment by Lysxia** [comment]
> This time can also be halved by adding HaRe as a dependency to the exe.

[Isn't it already?](https://github.com/RefactoringTools/HaRe/blob/master/HaRe.cabal#L221)

I hadn't thought about HaRe refactoring itself, what you say makes sense.

**Comment by alanz** [comment]
Hmm. Good point. Will have to check why it builds twice then. You can see the leftover commented dependencies for the tests for when it is not included as a library.

**Comment by Lysxia** [comment]
The reason is what I was trying to explain. To build the executable, which imports `Language.Haskell.Refact.HaRe` for instance, the compiler currently finds the file  `Language/Haskell/Refact/HaRe.hs` under the same directory, and compiles it as an independent module not part of any library. On the other hand, if the executable were in a separate directory, it would find no file matching the module name it is looking for, then search in the visible libraries, and use the already compiled module (as it should).

**Comment by alanz** [comment]
ok, that makes sense.
