### ISSUE TITLE
Incorrect renaming of function parameters

### ISSUE THREAD

**Issue by Lysxia** [RefactoringTools/HaRe#41]
```
module A where
  f x = let g = g in x
```

Rename `x` to `g` is successful, but shouldn't be as the result is not equivalent:

```
module A where
  f g = let g = g in g
```

**Comment by alanz** [comment]
Interesting. I am comparing the current implementation to the one in https://www.cs.kent.ac.uk/projects/refactor-fp/publications/Huiqing-thesis.pdf, and I see the in-place checking for each occurrence has got lost somewhere along the way.

Looks like a complete revalidation against the original will be required, for the various refactorings.

**Comment by alanz** [comment]
Closed via https://github.com/RefactoringTools/HaRe/pull/44
