### ISSUE TITLE
The GenApplicative refactoring does not use its FUNNAME parameter

### ISSUE THREAD

**Issue by alanz** [RefactoringTools/HaRe#55]
This is unnecessary, and should be deleted.

cc @SAdams601

**Comment by alanz** [comment]
While you are at it, https://github.com/RefactoringTools/HaRe/blob/master/src/Language/Haskell/Refact/Refactoring/GenApplicative.hs#L43 and the next line look like they should be wrapped in a `case` statement with error report on failure.

**Comment by alanz** [comment]
PS, I am working it into haskell-ide-engine at the moment

**Comment by SAdams601** [comment]
See pull request: https://github.com/RefactoringTools/HaRe/pull/56

**Comment by alanz** [comment]
Closed via https://github.com/RefactoringTools/HaRe/pull/56
